node . init --artistName "Kanye West" --albums "Yeezus"
node . init --artistName "Big Sean" --albums "I Decided" 
node . init --artistName "Jay Rock" --albums "Follow Me Home"
node . init --artistName "Wale" --albums "SHINE"
node . init --artistName "Kid Cudi" --albums "Passion, Pain & Demon Slayin"
node . init --artistName "J. Cole" --albums "2014 Forest Hills Drive" 
